name: Rago Build

on: [push]
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:  Build the Docker image
      run: docker build . --file Dockerfile -t light37/rago:$(date +%Y%m%d) -t light37/rago:latest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: light37/rago:latest 

